name: Build on Macos ARM64

on:
  workflow_dispatch:
#  push:
#    branches:
#      - master

jobs:
  build:
    runs-on: macos_arm64
    strategy:
      matrix:
        node: [ 16, 18, 20 ]
        libpg: [ 16 ]

    steps:
    - uses: actions/checkout@v4

    - name: Download libpq_query ${{ matrix.libpg }}-latest
      working-directory: ${{env.GITHUB_WORKSPACE}}
#      run: git clone -b "${{ matrix.libpg }}-latest" https://github.com/pganalyze/libpg_query.git
      run: git clone -b "master" https://github.com/MGorkov/libpg_query.git

    - name: Build libpg_query
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: |
        cd libpg_query
        make build
    
    - name: Setup Node.JS v${{ matrix.node }} and run install
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node }}
        architecture: ${{ matrix.architecture }}

    - name: Setup Python
      run: pip3 install setuptools
      
    - name: Install
      run: npm install

    - name: Package
      run: npm run binary:package

    - name: Publish
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.NODE_PRE_GYP_ACCESSKEYID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.NODE_PRE_GYP_SECRETACCESSKEY }}
      run: npm run binary:publish
